"""Compose the complete audit and invariant check from measured evidence."""
import json,math,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'renders/astra/v2_final_on_char'
def load(n):return json.loads((ROOT/'renders/astra'/n).read_text())
b=load('naturalness_metrics_before.json');a=load('naturalness_metrics_after.json')
bp=load('naturalness_before.json');ap=load('naturalness_after.json')
video=json.loads((OUT/'naturalness_video_verification.json').read_text())
def spans(values):
    vs=sorted(set(int(v) for v in values));out=[]
    if not vs:return 'none'
    start=end=vs[0]
    for v in vs[1:]:
        if v==end+1:end=v
        else:out.append(str(start) if start==end else f'{start}–{end}');start=end=v
    out.append(str(start) if start==end else f'{start}–{end}')
    return ', '.join(out)
def fmt(x):return f'{x:.2f}'
def maxjoint(m,k):return max((r[k],r['frame']) for r in m['joints'])
def evidence(fix):
    stem='naturalness_'+fix
    fs=video['evidence_order'][fix]
    return f"Evidence, left-to-right F{', F'.join(map(str,fs))}: [before](v2_final_on_char/{stem}_before.png), [after](v2_final_on_char/{stem}_after.png). Original-resolution matching frames are `v2_final_on_char/naturalness_before/NNN.png` and `v2_final_on_char/naturalness_after/NNN.png`."
def minlow(m):return min(r['margin_m'] for r in m['balance'] if 46<=r['frame']<=57)
def grounded(m,side):return [r['feet'][side+'Foot']['min_clearance_m'] for r in m['foot_floor']['rows'] if side=='Right' or r['frame']<=29 or r['frame']>=40]
def floor_min(m):return min((r['cloth_min_z']-m['foot_floor']['floor_z'],r['frame']) for r in m['foot_floor']['rows'])
def normalized_materials(p):
    mats=p['invariants']['materials'];out={}
    for n,d in mats.items():
        if d['props'].get('users',1)==0:continue
        d=json.loads(json.dumps(d));d['props'].pop('session_uid',None)
        out[n]=d
    return out
invariants={k:bp['invariants'][k]==ap['invariants'][k] for k in ['mesh_vertices_topology_weights_sha256','cameras','lights','render','eevee','image_settings','view_settings','world','rest']}
invariants['used_material_shader_data']=normalized_materials(bp)==normalized_materials(ap)
assert all(invariants.values()),invariants
unused_removed=sorted(set(bp['invariants']['materials'])-set(ap['invariants']['materials']))
verification={'invariants':invariants,'unused_material_ids_dropped_by_blender_save':unused_removed,'unchanged_camera_location':bp['invariants']['objects']['Astra_Camera']['matrix'],'newly_rendered_frames':90,'video':video,'visual_review_complete':False,'scope':'only existing rig/blur translation F-curves edited; no camera/light/render-engine/geometry/weights/rest-hierarchy changes','source_blend_sha256':hashlib.sha256((ROOT/'models/astra_xslash_v2_final_prefix.blend').read_bytes()).hexdigest(),'fixed_blend_sha256':hashlib.sha256((ROOT/'models/astra_xslash_v2_final_wip.blend').read_bytes()).hexdigest()}
(ROOT/'renders/astra/naturalness_verification.json').write_text(json.dumps(verification,indent=2))
lines=[]
def add(s=''):lines.append(s)
add('# Godwyn X-slash naturalness audit — 90-frame final revision')
add('\nAudited the approved final scene, corrected its existing animation, and re-rendered F1–90. This is **an improvement with documented residual issues**, not a claim of a physically simulated or collision-free character. The major arm flips, backward wrist bend, elbow over-fold and severe hem sinking were real. The anticipation already had acceleration shaping; the low F46–57 poses already had good support margins.\n')
add('## Deliverables and scope')
add('\n- Fixed scene: `models/astra_xslash_v2_final_wip.blend`; original scene retained at `models/astra_xslash_v2_final_prefix.blend`.\n- Shippable clip: `renders/astra/godwyn_xslash_v2_final.mp4`; original retained at `renders/astra/godwyn_xslash_v2_final_prefix.mp4`.\n- [Before metrics](naturalness_metrics_before.json), [after metrics](naturalness_metrics_after.json), [invariant verification](naturalness_verification.json).\n- [Before evaluation sheet](v2_final_on_char/naturalness_before_evaluation_sheet.png), [after evaluation sheet](v2_final_on_char/naturalness_after_evaluation_sheet.png). Frame order: '+', '.join(map(str,video['evaluation_frames']))+'.\n')
add('All authoring changes are existing pose-bone rotation/location keys, plus location keys on the existing blur ribbons to follow the small corrected first-cut grip displacement. Mesh vertices, topology, skin weights, bone rest hierarchy, used material shaders, lighting, camera, world, EEVEE settings, exposure and image settings compare unchanged. Blender discarded two unused material IDs during normal save/reload (`Astra charcoal`, `GodwynGameMat`); no used shader or material assignment was authored. No cinematography paths, character sources, SPEC.txt or CLAUDE.md were written. No network, installs or git commands were used.\n')
add('**Framing constraint:** the saved final blend uses the front orthographic camera (scale 5.4). The prior MP4 used a temporary three-quarter override. The user reiterated no camera changes, so the new clip and all before/after evaluation images use the unchanged saved front camera. This accounts for the framing difference from the backed-up MP4.\n')
add('## Measurement method and limits')
add(f'\n- Sampled **{a["bone_count"]} bones, {a["curve_count"]} F-curves and {a["key_count"]:,} existing keys** at all 90 integer frames and all 357 quarter frames. Maximum source key spacing is {a["max_key_gap"]:.2f} frame; interpolation is Bézier with clamped automatic handles. Quaternion components, scalar derivatives and world/parent-space transforms are retained in the raw JSON.\n- Rotation velocity uses the shortest quaternion logarithm of `q_next * inverse(q_previous)`, expressed in degrees/frame. This avoids mistaking antipodal quaternion signs for flips. At 30 fps, multiply speed by 30 and acceleration by 900 for per-second units. We also retain scalar component sign reversals; these alone are not anatomical defects.\n- Automated candidate thresholds: direction dot below −0.5 with both adjacent angular steps above 0.5°; speed above both 4°/frame and 2.8× its local seven-sample median; angular acceleration above 12°/frame². These are audit flags, not hard human limits. All flagged bones/frames have a disposition below.\n- Major-bone head velocities/accelerations and quarter-frame angular peaks cover every non-cloth bone. Imported display tails are approximately 100× too long, so limb lengths and COM use joint heads; wrist longitudinal direction uses the normalized hand orientation.\n- Elbow flexion is 0° at straight, not the interior elbow angle. Wrist bend is the forearm/hand-long-axis angle; the rest wrist itself is angled. A broad 80° warning and 150° elbow-flexion warning are screening thresholds, not a calibrated anatomical constraint rig. Separate radial/ulnar deviation and forearm pronation cannot be fully certified from these imported axes.\n- COM proxy: torso 49.7%, head 8.1%; each thigh 10%, shank 4.65%, foot 1.45%, upper arm 2.8%, forearm 1.6%, hand 0.6%. Segment centers use interpolated joint heads. Support hull uses a 20 cm boot width, 12 cm heel extension and 9 cm beyond the toe joint; a 2 cm inset is the conservative margin. Left support is F1–29 and F40–90, right support F1–90. Actual sword landmarks supply 2%, 4%, 6% body-mass sensitivity checks.\n- Foot/cloth surface tests evaluate the real skinned mesh at every integer frame against the actual stage plane, Z = −0.015 m. Sole selection uses low vertices predominantly weighted to foot/toe bones. Cloth-leg capsule proximity is only a candidate test: shared skinning regions and covered legs prevent treating every close vertex as an intersection.\n- Timing and lean measurements are kinematic evidence. They do not measure torque, ground reaction forces, inertial tensors or fabric physics.\n')
add('## Defects corrected')
add('\n### 01 — Major: sword-arm flips and teleports, F37–40 and F53–55')
add(f'\nBefore: RightForeArm rotated **{b["peaks"]["RightForeArm"]["speed_deg_frame"]:.2f}° in F38→39**, with {b["peaks"]["RightForeArm"]["accel_deg_frame2"]:.2f}°/frame² peak acceleration. RightArm jumped {b["peaks"]["RightArm"]["speed_deg_frame"]:.2f}° at F54. The right elbow moved **{b["major_translation"]["RightForeArm"]["peak_head_step_m"]*100:.2f} cm in one frame**, F53→54; subframe upper-arm speed peaked at {b["major_translation"]["RightArm"]["quarter_frame_peak_rotation_deg_frame"]:.2f}°/frame. Visuals show the forearm/gauntlet whipping around the arm rather than following one hinge plane.\n')
add(f'Fix: replaced singular independent pole/aim orientations with continuous elbow-circle selection, smoothed pole travel and a consistent anatomical bend-plane frame; baked onto the existing quarter-frame channels. After: right forearm peak {a["peaks"]["RightForeArm"]["speed_deg_frame"]:.2f}°/frame, acceleration {a["peaks"]["RightForeArm"]["accel_deg_frame2"]:.2f}°/frame²; elbow head step {a["major_translation"]["RightForeArm"]["peak_head_step_m"]*100:.2f} cm; upper-arm subframe peak {a["major_translation"]["RightArm"]["quarter_frame_peak_rotation_deg_frame"]:.2f}°/frame. The large one-frame flips are gone. Fast continuous slash acceleration remains and is disclosed below.\n'+evidence('01_arm_pops'))
add('\n### 02 — Major: backward sword wrist, F1–16, F39 and F74–90')
add(f'\nBefore: forearm/hand bend peaked at **{maxjoint(b,"Right_wrist_bend")[0]:.2f}° at F{maxjoint(b,"Right_wrist_bend")[1]}**, with 127.61° already at F1. This is not merely forearm roll. Fix: the continuous elbow solve favors a supported palm and penalizes excessive hand bend while retaining the world blade orientation. After: maximum {maxjoint(a,"Right_wrist_bend")[0]:.2f}° at F{maxjoint(a,"Right_wrist_bend")[1]}; no frame exceeds the broad 80° screening threshold. Some 65–71° loaded poses remain stylized, not an anatomically certified grip.\n'+evidence('02_sword_wrist'))
add('\n### 03 — Major: sword elbow over-fold, F38–40, worst F39')
add(f'\nBefore: **{maxjoint(b,"Right_elbow_flexion")[0]:.2f}°** flexion at F39 folds the armored forearm almost back into the upper arm. Fix: smoothly extend the grip forward by up to 18 cm, F36.5–42, and re-solve the arm. After: maximum **{maxjoint(a,"Right_elbow_flexion")[0]:.2f}°** at F39. Limb lengths remain fixed; no bone rest edit or scaling was used. Existing first-cut ribbon objects receive the matching shutter-midpoint translation keys. Their baked shape is retained; a small subframe ribbon/path mismatch is acknowledged below.\n'+evidence('03_elbow_fold'))
add('\n### 04 — Moderate: off-arm hinge kink, F40–44 and F52')
add(f'\nBefore: LeftForeArm peak {b["peaks"]["LeftForeArm"]["speed_deg_frame"]:.2f}°/frame; acceleration {b["peaks"]["LeftForeArm"]["accel_deg_frame2"]:.2f}°/frame² at F43; reversal F43 flips from 3.06° to 14.63° per frame. Fix: smooth the elbow pole and use a consistent hinge plane while preserving the off-hand position track. After: peak {a["peaks"]["LeftForeArm"]["speed_deg_frame"]:.2f}°/frame and acceleration {a["peaks"]["LeftForeArm"]["accel_deg_frame2"]:.2f}°/frame². Direction reversals at recoil extrema still occur, but the sharp twist is reduced. The specifically requested F36/F46 checks do **not** show elbow hyperextension; source flexion was 115.08°/72.63°.\n'+evidence('04_off_arm_kink'))
add('\n### 05 — Minor: shoulders in identical timing, F1–90, most visible F34–40/F51–57')
add(f'\nBefore: left/right clavicle speed correlation at zero lag {b["symmetry"]["LeftShoulder/RightShoulder"]["speed_correlation_zero_lag"]:.6f}, with both local peaks at F38.25 and F55.25. Fix: delay the off shoulder by two frames. After: zero-lag correlation {a["symmetry"]["LeftShoulder/RightShoulder"]["speed_correlation_zero_lag"]:.6f}, best match at +2 frames; off-shoulder peaks F40.25/F57.25. The original arm/hand target paths were already asymmetric, so no wholesale mirrored-limb problem is claimed.\n'+evidence('05_shoulder_timing'))
add('\n### 06 — Minor: off-hand wrist rigidly locked, F1–90')
add('\nBefore: all left-hand local rotation keys were constant; rest-relative wrist swing was zero throughout. Fix: a small delayed wrist response, −2° to +2.5°, following the arm phases. After: maximum 2.50° rest-relative swing while anatomical forearm/hand bend remains approximately 18.82–19.35°. This removes the absolute wrist lock without adding a conspicuous gesture.\n'+evidence('06_off_hand_rigidity'))
add('\n### 07 — Moderate: missing wind-up sword-mass counter-lean, F13–30')
add('\nBefore: torso lean toward the horizontal blade direction was +0.81° at F13, +0.33° at F20 and +0.21° at F27: little opposing lean. Fix: distribute a gentle 3.5° world counter-lean across the three spine channels during anticipation, fading out by F37; hand targets stay in place. After: −0.21°, −1.40°, −1.66° respectively. Negative means away from the blade. Existing forward pull during cuts remains: +7.62° at F39 and +8.24° at F57. This adds visible weight response while retaining the authored attack timing.\n'+evidence('07_counterlean'))
add('\n### 08 — Minor: repeated settling bob, F80–90, reversals around F82/F86')
add(f'\nBefore: the sword hand traversed {b["windows"]["80-90"]["RightHand"]["travel_m"]*100:.2f} cm through multiple small stop/restart lobes. Fix: replace the late position lobes with one tangent-continuous arrival and a single return to the final guard. After: {a["windows"]["80-90"]["RightHand"]["travel_m"]*100:.2f} cm, preserving the arrival velocity and F90 endpoint. This is a damped settling change, **not** a fix for linear interpolation: the original curves were already accelerated.\n'+evidence('08_settle_bob'))
add('\n### 09 — Minor: planted boot hover/penetration, F1–29/F40–90 left; F1–90 right')
add(f'\nBefore evaluated sole clearance: left **{min(grounded(b,"Left"))*1000:.2f} to {max(grounded(b,"Left"))*1000:.2f} mm**, right **{min(grounded(b,"Right"))*1000:.2f} to {max(grounded(b,"Right"))*1000:.2f} mm**. Left sinking is worst at F58; floating is visible numerically around F40–49 and F76–90. Constant ankle height alone had hidden this skin-deformation error. Fix: offset the foot target by measured sole clearance and re-solve the leg with fixed segment lengths and foot orientation. After: left {min(grounded(a,"Left"))*1000:.2f}–{max(grounded(a,"Left"))*1000:.2f} mm; right {min(grounded(a,"Right"))*1000:.2f}–{max(grounded(a,"Right"))*1000:.2f} mm. Every sampled planted sole is above the plane and within the 5 mm visual contact tolerance.\n'+evidence('09_foot_contact'))
add('\n### 10 — Minor: cloth co-rotation too immediate during the cuts, F31–60')
add('\nThe source was **not** devoid of lag: hem extrema already followed the hips, and no convincing hem-leading event was found. However, the strongest robe world-yaw velocity correlation was at zero delay, with the hem correlation about 0.98, so the fast motion was dominated by inherited pelvis rotation. The delayed local pulses largely cancelled in the accumulated chain. Fix: cumulative delayed, critically damped yaw compensation, small left/right panel offsets, and a smooth ending envelope; replace the explicit recovery sine response. After: robe velocity best delay is +1 frame, cape +2 (the search includes −10 to +20, so leading is not silently excluded). Central robe hem extrema are F49/F68 versus hips F44/F62, and the cape hem F49/F69. The source hem extrema were F48/F69 and F49/F67 respectively: improvement is in the fast response and damping, not a claim that all original follow-through was wrong.\n'+evidence('10_cloth_lag'))
add('\n### 11 — Major, now minor residual: cloth buried in the stage, especially F38–43/F53–61')
add(f'\nBefore: lowest sampled cloth point was **{abs(floor_min(b)[0])*100:.2f} cm below the floor at F{floor_min(b)[1]}**, caused by the lowered pelvis pulling the hanging hem into the stage. Fix: add measured, progressively distributed upward location corrections to existing distal cloth links; waist/spine roots and the first three links remain attached. Three measured correction passes let the lower fabric gather rather than disappear. After: deepest residual **{abs(floor_min(a)[0])*100:.2f} cm at F{floor_min(a)[1]}**, a {100*(1-abs(floor_min(a)[0]/floor_min(b)[0])):.1f}% reduction. The rendered hem now pools visibly at the ground through the low poses.\n')
add('Residual penetration above 3 mm occurs at F'+spans(r['frame'] for r in a['foot_floor']['rows'] if r['cloth_min_z']-a['foot_floor']['floor_z']<-.003)+'. **Not fully fixed:** the last small penetration comes from blended panel vertices; more shortening visibly compresses the hem, and correcting the binding/geometry is outside this animation-only pass. This is an explicit residual, not a collision-free claim.\n'+evidence('11_hem_floor'))
add('\n## Defects and risks retained, with reasons')
add(f'\n- **Moderate groundedness warning, F30–39:** static COM is outside the right-foot-only support hull. Worst source deficit {abs(min(r["margin_m"] for r in b["balance"]))*100:.2f} cm at F39; after {abs(min(r["margin_m"] for r in a["balance"]))*100:.2f} cm. The counter-lean/arm changes marginally worsen this proxy by about 0.45 cm; this is not hidden. The 2–6% sword-mass sensitivity does not eliminate the warning. **Not fixed:** this is a moving step caught by left-foot contact at F40, so static COM alone cannot establish an impossible fall. A guaranteed single-foot balance fix requires reblocking the approved step/whole-body translation, with significant knock-on effects on both cuts. No false claim of dynamically stable balance is made.\n')
add('- **Minor residual knee settling reversals, F46/F79:** original right knee reversed at F46 and both knees at F79. Sole correction adds small corresponding thigh/knee responses. **Not fixed further:** these coincide with the intentional pelvis rise/rebound, have no positional teleport, and are small compared with the corrected arm defects. Flattening them would alter the approved weight-settle timing.\n')
add('- **Moderate stylistic acceleration, F36–40/F53–55/F60–62:** some arm acceleration flags remain after the flips are removed. **Retained:** the blade still executes the approved fast cuts; high velocity alone is not a discontinuity. Every remaining flagged frame is listed below. A force/mass simulation would be needed to certify human-achievable torque.\n')
add('- **Minor residual endpoint motion, F89–90:** local cloth channels approach rest, but inherited spine motion keeps the cape moving slightly at the clip end (central cape tip approximately '+fmt(a['cloth']['phys_cape_C_06']['end_world_speed_deg_frame'])+'°/frame; central robe tip '+fmt(a['cloth']['phys_robe_back_C_07']['end_world_speed_deg_frame'])+'°/frame). **Retained:** small continuous follow-through is preferable to forcibly locking the parent spine at the final frame. This clip is not asserted to be a seamless loop.\n')
add('- **Minor approximation, blur ribbons F38–41:** the small first-cut grip extension is carried by existing ribbon translation keys at the shutter midpoint. **Not rebuilt:** an exact new curved ribbon would require vertex/geometry edits prohibited by this pass. The rendered result must be judged with this known approximation; the blade itself follows the corrected arm.\n')
add('- **Unconfirmed cloth/leg clipping candidates, strongest around F57–58 and F69–73:** source cloth-weighted vertices approach leg capsule axes to sub-millimeter distances. These samples can include covered/shared skinning regions and do not prove an actual exposed-surface intersection. **No additional edit:** changing cloth to avoid every capsule would create hovering fabric and could move the front tabard away from the belt. The audit does not certify hidden cloth/leg collision clearance. The visible 640 px frames are the confirmation limit.\n')
add('## Checks that were already good, and what the numbers do not imply')
add(f'\n**Anticipation/settle interpolation:** there are no sparse linear limb curves to repair. F13–27 speed CVs were hips {b["windows"]["13-27"]["Hips"]["cv"]:.3f}, sword hand {b["windows"]["13-27"]["RightHand"]["cv"]:.3f}, off-hand {b["windows"]["13-27"]["LeftHand"]["cv"]:.3f}; the sword-hand step falls from 46.26 mm to 4.76 mm. F80–90 source sword-hand CV was {b["windows"]["80-90"]["RightHand"]["cv"]:.3f}. These are changing-speed paths, not constant-speed drifting. The only settle defect addressed is the repeated bob.\n')
add(f'**Low-pose balance:** F46–57 source minimum static support margin is **{minlow(b)*100:.2f} cm**, after **{minlow(a)*100:.2f} cm**, comfortably inside the 2 cm inset. No unsupported-low-pose defect was invented.\n')
add('**Momentum cascade:** the source already leads from hips through the three local spine channels: first cut peaks F34.25 → 35.25 → 36.25 → 37.25 → right clavicle 38.25; second cut 51.25 → 52.25 → 53.25 → 54.25 → 55.25. These local timings remain. In world space after correction, first cut hips 34.25 → upper spine 35.25 → right shoulder 35.5 → upper arm 39.0 → wrist 39.5; second cut 51.25 → 52.25 → 52.5 → upper arm 54.5 → forearm 54.75 → wrist 56.25. Thus the visible motion originates lower in the chain, rather than the torso and sword starting together. Local relative-joint speed peaks are not all monotonic—wrist compensation and elbow flexion can peak at different times—so an exact torque cascade is not claimed from F-curves. The corrected planted right sole provides a visible ground contact, with the single-support COM caveat above.\n')
add(f'**Elbow/knee extension:** after correction, right elbow flexion remains {min(r["Right_elbow_flexion"] for r in a["joints"]):.2f}–{maxjoint(a,"Right_elbow_flexion")[0]:.2f}°, left {min(r["Left_elbow_flexion"] for r in a["joints"]):.2f}–{maxjoint(a,"Left_elbow_flexion")[0]:.2f}°. Neither passes through straight into a measured backward knee/elbow bend. A unsigned segment-angle test alone cannot prove the anatomical hinge sign; consistent bend-plane construction and visuals provide the additional check.\n')
add(f'**Sword/cloth proximity:** source closest sampled cloth vertex to the grip–tip centerline was {min(r["cloth_sword_min_vertex_centerline_m"] for r in b["foot_floor"]["rows"])*100:.2f} cm; after {min(r["cloth_sword_min_vertex_centerline_m"] for r in a["foot_floor"]["rows"])*100:.2f} cm. No sword-through-hem event was confirmed. This is a vertex/centerline proximity test, not an exact triangle collision solver.\n')
add('**Tabard/surcoat observation:** `phys_robe_front_*`, `phys_robe_side_*` and `phys_robe_back_*` roots are parented to Hips, consistent with belt anchoring. `phys_cape_*` roots are parented to Spine and represent a separate upper-body trailing system. The rig therefore supports more than one front panel; it does not imply that the blue front panel is shoulder-hung. The visible silhouette includes full side/back drapes as well as the front tabard. Per the scope restriction, no geometry, naming or hierarchy was restructured to reinterpret SPEC.txt.\n')
add('## Full automated candidate disposition')
add(f'\nThe thresholds emitted {len(b["events"])} source angular events and {len(a["events"])} after events. Each bone below includes every flagged integer frame. Scalar component extrema ({len(b["scalar_reversals"])} before / {len(a["scalar_reversals"])} after) are retained individually in the metrics JSON; they are not independently called defects when the quaternion motion remains continuous.\n')
for n in sorted(set(e['bone'] for e in b['events']+a['events'])):
    be=[e for e in b['events'] if e['bone']==n];ae=[e for e in a['events'] if e['bone']==n]
    reason=('Major source defects corrected as 01–03; remaining flags are cut acceleration and continuous flexion/release extrema, retained for approved timing.' if n.startswith('Right') and any(t in n for t in ['Arm','Hand']) else 'Moderate source kink reduced as 04; remaining extrema are recoil/flexion changes, retained.' if n in ['LeftArm','LeftForeArm'] else 'Minor pelvis-driven settle/recoil response; retained to preserve weight timing and foot contact.')
    add(f'- **{n}:** source F{spans(e["frame"] for e in be)}; after F{spans(e["frame"] for e in ae)}. {reason}')
add('\nAll major-bone position and quarter-frame angular maxima are in `major_translation` in both metric files; all 121 bone angular maxima are in `peaks`. The right elbow was the unequivocal position discontinuity (84 cm/frame). Its correction does not make the hand slow: the largest remaining hand step occurs within the intentional fast cut, not an unkeyed teleport.\n')
add('## Reproduction and review evidence')
add('\nUse Blender 5.2.1 at `/opt/homebrew/bin/blender`, `--background --gpu-backend metal --python-exit-code 1`. The reproducible animation edit is `scripts/astra_xslash_naturalness_fix.py` reading the immutable prefix and the original sampled data; follow with `scripts/astra_xslash_naturalness_ground_cloth.py` three times. The surface/probe/analyze scripts produce the before/after JSON. `scripts/astra_xslash_naturalness_render.py -- after` renders the saved scene; `scripts/astra_xslash_naturalness_package.py` makes evidence sheets and overwrites the required MP4.\n')
add('Evidence includes all 90 newly rendered PNGs, 20 matching before/after evaluation poses, 11 pairs of defect-specific sheets, and six consecutive sheets decoded from the actual final MP4. Within each defect sheet, frame order is printed in that defect’s entry. The decode is H.264/yuv420p, 640×640, 30 fps, exactly 90 frames / 3.0 s, and completes without errors.\n')
add('Visual review status is recorded separately in `naturalness_verification.json`; the final completion update is appended after inspecting all six decoded sheets.\n')
(ROOT/'renders/astra/naturalness_audit.md').write_text('\n'.join(lines))
print('AUDIT REPORT WRITTEN',len('\n'.join(lines).split()),'words')
