"""Append the measured sword-arm follow-up without replacing the prior audit."""
import json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];D=ROOT/'renders/astra'
def read(n):return json.loads((D/n).read_text())
r=read('naturalness_armfix_verification.json');sub=read('naturalness_armfix_subframes.json');m=read('naturalness_metrics_armfix.json');v=read('v2_final_on_char/armfix_video_verification.json')
assert all(r['gates'].values()) and v['frames']==90 and v['full_decode_error_free']
assert v['scene_sha256']==r['candidate_sha256']==hashlib.sha256((ROOT/'models/astra_xslash_v2_final_wip.blend').read_bytes()).hexdigest()
assert v['sha256']==hashlib.sha256((D/'godwyn_xslash_v2_final.mp4').read_bytes()).hexdigest()
text=f'''

## Sword-arm follow-up — 2026-09-06

This section supersedes the earlier wrist/cascade conclusions for the current final. Trigger: the independently reported X-slash wrist-deviation and upper-arm/forearm timing findings in [the read-only arm audit](armaudit/defects_xslash.md). Both were independently reproduced from the actual approved scene using our existing probe/analyzer. No incomplete geometry or penetration claim from that audit is accepted as verified. Backup: `models/astra_xslash_v2_final_prefix2.blend` (SHA-256 `{r['source_sha256']}`); the older `_prefix.blend` remains untouched.

- **X01 — major, F45–51, maximum F47.25: excessive sword-wrist lateral deviation. Fixed.** The hand-frame lateral screen reproduced **−46.7653° at F47.25**. F46/F47/F48 were **−43.1115°/−46.7576°/−45.1908°**; all three and F47.25 are now **−25.0000°**. The full-clip quarter-frame range is **−29.3687° (F45) to +14.6236° (F77)**, inside ±30°. F44 **−22.5743°** and F53 **−19.8742°** retain their exact original pose values. The elbow travels around its fixed-length reach circle (maximum pole rotation **31.27°**) with smooth F44–46/F51–53 ramps; forearm and hand rotations compensate to retain the weapon binding. Total wrist-bend maximum improves **70.7106° → 59.7225°**. Evidence: [before F44–53](v2_final_on_char/armfix_wrist_before.png), [after F44–53](v2_final_on_char/armfix_wrist_after.png), [paired F46/F47/F48](v2_final_on_char/armfix_wrist_comparison.png), individual [before F47](v2_final_on_char/armfix_before/047.png) / [after F47](v2_final_on_char/armfix_after/047.png). The two ten-pose wrist sheets both use F44,45,46,47,48,49,50,51,52,53 in row order.

- **X02 — moderate, first-cut F39: simultaneous upper-arm/forearm speed peaks. Fixed.** RightArm remains **57.7710°/frame at F39.00**; RightForeArm changes **57.7418°/frame at F39.00 → 54.8305°/frame at F39.50**. The measured delay is **0 → 0.50 frame**. The clavicle still leads at F35.50. A bounded F34–44 forearm axial-roll retiming (maximum **23.11°** offset) produces the delay while a compensating hand rotation preserves the sword. RightHand world peak remains **45.6251°/frame at F39.50**. At the finer 1/64-frame sampling, the actual upper/fore peaks are F38.875/F39.28125: a **0.40625-frame** lead, showing the quarter-frame 0.50 value is a sampled estimate. Blade peak timing remains F39.484375; its measured finer-grid peak changes by only **0.00954°/frame**. Evidence: [before F36–41](v2_final_on_char/armfix_cascade_before.png), [after F36–41](v2_final_on_char/armfix_cascade_after.png), [paired F38/F39/F40](v2_final_on_char/armfix_cascade_comparison.png).

**Regression checks and retained findings.** All 90 integer frames and 357 quarter-frame poses were rechecked in [the gate-of-record metrics](naturalness_metrics_armfix.json), against [the freshly reproduced baseline](naturalness_metrics_armfix_before.json). Only RightArm/RightForeArm/RightHand quaternion curves changed; 5,264 extra keys give 1/32-frame sampling within the edit windows. All other animation channels and the mesh, weights, rest rig, materials, lights, camera, and EEVEE settings compare unchanged. Right-elbow quarter-frame maximum stays **148.2167°**, below 150°; finer sampling reaches **148.2183°**. Actual planted sole clearances remain exactly **1.009–3.621 mm left / 1.386–2.858 mm right**, with no sampled penetration. Every cloth lag metric and cloth-floor minimum is exactly unchanged.

- **Minor retained numerical balance change, F45–52:** the low-pose body-COM margin minimum is **183.3766 → 182.8766 mm at F47** (−0.5000 mm); the largest individual decrease is **0.8552 mm at F51**, whose remaining margin is 221.6962 mm. This is explicitly a small numerical decrease, not an exact balance improvement. It is retained because it is below a 1 mm comparison tolerance for the approximate segment-mass/support model and remains far inside the existing 20 mm inset; changing unrelated body keys to cancel it would overfit the proxy. The prior single-support warning remains **−307.6440 mm at F39**, unchanged, with no new outside-support frames.
- **Minor retained relative-rotation screening flags:** new >12°/frame² flags occur on RightArm F52 (**12.30**), RightForeArm F45/F46 (**14.22/19.56**), and RightHand F45/F53 (**12.74/12.14**); RightHand has a local counter-rotation reversal at F40 (**12.08 → 4.77°/frame**, direction dot **−0.974**). Forearm maximum local acceleration rises **19.12 → 26.80°/frame² at F39** as its timing separates from the upper arm. These are continuous elbow-pole/compensating-roll transitions, retained after subframe and visual review to preserve the weapon trajectory; they are not described as a perfectly clean set of curves. Upper-arm/hand maximum local angular acceleration and all three maximum integer head steps remain unchanged. The elbow-head acceleration maximum rises **85.85 → 98.59 mm/frame²**, moving from F36 to F45; this modest increase is another retained consequence of fitting the pole change between the locked endpoints. See the complete event arrays in the metrics.

World binding verification: maximum quarter-frame hand drift **{r['hand_world_position_max_error_m']*1000:.6f} mm / {r['hand_world_rotation_max_error_deg']:.6f}°**; actual integer sword tip/grip differences **{r['blade_max_error_m']['sword_tip']*1000:.6f}/{r['blade_max_error_m']['sword_grip']*1000:.6f} mm**. The independent 1/64-frame check across F33–54 limits between-key hand drift to **0.0481 mm / 0.00287°**. These finite-precision tolerances are recorded, rather than claiming mathematically exact motion between every key. See [subframe results](naturalness_armfix_subframes.json) and [invariant/regression verification](naturalness_armfix_verification.json). Hidden armor/cloth triangle intersections remain unverified; the saved front-view evidence shows no new exposed breakthrough.

All 90 frames were re-rendered in **BLENDER_EEVEE**, using the existing saved scene settings, and encoded in place as [the final MP4](godwyn_xslash_v2_final.mp4): **640×640, 30 fps, 90 frames, 3.0 s, H.264/yuv420p**, full decode error-free. Focused poses and paired sheets were inspected, followed by all six consecutive sheets decoded from the actual new MP4 (`v2_final_on_char/armfix_decoded_01.png` through `06.png`, F1–90). [Video verification](v2_final_on_char/armfix_video_verification.json) records hashes and frame order. Final scene SHA-256: `{v['scene_sha256']}`; MP4 SHA-256: `{v['sha256']}`.

Reproduction: `scripts/astra_xslash_armfix_apply.py` reads the immutable prefix2 and writes a candidate; the existing probe/surface/analyze scripts, then `astra_xslash_armfix_verify.py` and `astra_xslash_armfix_subframes.py`, supply numerical checks. The verified candidate was copied byte-for-byte to `models/astra_xslash_v2_final_wip.blend`. `astra_xslash_naturalness_render.py -- after` and `astra_xslash_armfix_package.py` render/package the deliverable. No cinematography, character, move-track, or arm-audit file was written.
'''
p=D/'naturalness_audit.md';old=p.read_text();assert '## Sword-arm follow-up — 2026-09-06' not in old
p.write_text(old.rstrip()+text+'\n')
print('APPENDED AUDIT SECTION AT LINE',len(old.rstrip().splitlines())+2)
