import bpy,sys,json,numpy as np
from pathlib import Path
from mathutils import Vector
from mathutils.bvhtree import BVHTree
R=Path(__file__).resolve().parents[1];sys.path.insert(0,str(R/'scripts'));import astra_v3m_audit as a;import astra_v3m_publish as p
O=R/'renders/astra/v4p';bpy.ops.wm.open_mainfile(filepath=str(O/'candidate.blend'));rig=bpy.data.objects['Astra_V4_Rig'];body=bpy.data.objects['V4_Body'];sword=bpy.data.objects['Godwyn_Sword'];clip=sys.argv[sys.argv.index('--clip')+1] if '--clip' in sys.argv else 'Combat_Stance';act=bpy.data.actions[clip];rest=np.array([(body.matrix_world@v.co)[:] for v in body.data.vertices]);edges,lengths,valid=a.body_edge_data(body,rest);soles=a.sole_ids(body);bodyfaces=[tuple(f.vertices) for f in body.data.polygons];src=np.array([v.vector[:] for v in sword.data.attributes['astra_sword_source'].data]);bladeids=np.where(src[:,2]<150)[0];bladefaces=[tuple(f.vertices) for f in sword.data.polygons if all(src[i,2]<150 for i in f.vertices)];swordfaces=[tuple(f.vertices) for f in sword.data.polygons];names={g.index:g.name for g in body.vertex_groups};handverts={v.index for v in body.data.vertices if sum(g.weight for g in v.groups if names[g.group]=='RightHand')>.5};handfaces=[tuple(f.vertices) for f in body.data.polygons if all(i in handverts for i in f.vertices)];outsidefaces=[tuple(f.vertices) for f in body.data.polygons if not all(i in handverts for i in f.vertices)];fit=np.linalg.lstsq(np.column_stack((src,np.ones(len(src)))),np.array([v.co[:] for v in sword.data.vertices]),rcond=None)[0];hiltlocal=Vector(np.array([61.2,-66.3,167,1.])@fit);rig.data.pose_position='REST';bpy.context.view_layer.update();swrest,_=a.evaluated(sword);hp=sword.matrix_world@hiltlocal;ht=a.tree(rest,handfaces);near=ht.find_nearest(hp);depth=-float((hp-near[0]).dot(near[1]));grip={'hilt_reference_world_m':list(hp),'signed_normal_depth_m':depth,'nearest_surface_distance_m':near[3],'definition':'v3 handle center marker fitted from astra_sword_source; signed distance against nearest right-hand surface normal, positive inward. Open fingers mean this does not certify a closed fist.','right_hand_faces':len(handfaces),'right_hand_vertices':len(handverts)}
rig.data.pose_position='POSE';rows=[]
for frame in range(1,int(act.frame_range[1])+1):
 a.assign(rig,act,frame);bp,_=a.evaluated(body);sp,_=a.evaluated(sword);ratios=np.linalg.norm(bp[edges[:,0]]-bp[edges[:,1]],axis=1)[valid]/lengths[valid];bt=a.tree(bp,bodyfaces);blade=a.tree(sp,bladefaces);whole=a.tree(sp,swordfaces);outside=a.tree(bp,outsidefaces);foot={n:float(bp[ix,2].min()) for n,ix in soles.items()};row={'frame':frame,'stretch_p99':float(np.percentile(ratios,99)),'stretch_max':float(ratios.max()),'body_min_z_m':float(bp[:,2].min()),'soles_m':foot,'blade_min_z_m':float(sp[bladeids,2].min()),'blade_body_triangle_pairs':len(bt.overlap(blade)),'whole_sword_body_triangle_pairs':len(bt.overlap(whole)),'sword_non_grip_body_triangle_pairs':len(outside.overlap(whole))};rows.append(row)
 if frame%10==0 or frame==1:print('V4_AUDIT_FRAME',json.dumps(row),flush=True)
rep={'clip':clip,'frames':len(rows),'body_min_z_m':min(r['body_min_z_m'] for r in rows),'stretch_max':max(r['stretch_max'] for r in rows),'stretch_p99_max':max(r['stretch_p99'] for r in rows),'stretch_gate':2.2,'lowest_planted_sole_min_m':min(min(r['soles_m'].values()) for r in rows),'lowest_planted_sole_max_m':max(min(r['soles_m'].values()) for r in rows),'blade_min_z_m':min(r['blade_min_z_m'] for r in rows),'blade_body_pairs_max':max(r['blade_body_triangle_pairs'] for r in rows),'sword_non_grip_body_pairs_max':max(r['sword_non_grip_body_triangle_pairs'] for r in rows),'whole_sword_body_pairs_max':max(r['whole_sword_body_triangle_pairs'] for r in rows),'grip':grip,'weights':p.weight_audit([body,sword],rig),'rows':rows};rep['mechanical_pass']=rep['stretch_p99_max']<=2.2 and rep['body_min_z_m']>=-.02 and max(abs(rep['lowest_planted_sole_min_m']),abs(rep['lowest_planted_sole_max_m']))<=.005 and rep['blade_min_z_m']>=-.02 and rep['sword_non_grip_body_pairs_max']==0 and rep['blade_body_pairs_max']==0;(O/(clip+'_audit.json')).write_text(json.dumps(rep,indent=2));print('V4_AUDIT',json.dumps({k:v for k,v in rep.items() if k!='rows'}),flush=True)
